### ISSUE TITLE
Add support to read .zoo.yml while scanning a git repo

### ISSUE THREAD

**Issue by imunitic** [kiwicom/the-zoo#254]
Make zoo scan for .zoo.yml file in a git repo. This file should contain all necessary metadata about the project being scanned. Zoo upon reading this file can create or update a project in its registry.

If a project already exists in the registry zoos behavior should be configurable to either overwrite or do nothing. Something like override-existing: false in the yaml file.

The exact content and structure of .zoo.yml is still up for debate.

**Comment by imunitic** [comment]
Here is a first draft of how .zoo.yml could look like.
```yaml
zoo:
  register:
    type: service
    name: hello-world-service
    owner: johndoe
    impact: profit
    status: production
    repository: https://git/hello-world-service.git
    documentation-url: https://docu.com/hello-world-service
    slack-channel: http://slack.com/channel
    sentry-project: http://sentry.com/hello-world-service
    sonarqube-key: hello-world-service
    pager-duty-url: https://pager.com/pager/hello-world-service
    tags:
      - tag1
      - tag2
      - tag3
    environments:
      - staging:
          dashboard-url: https://staging.dashboard-url.com
          service-url: https://staging.service-url.com
      - production:
          dashboard-url: https://production.dashboard-url.com
          service-url: https://production.service-url.com
  actions:
    on-exists: update # possible values update | skip 
```

For now the file has two sections called register and actions. Register is where the metadata for the project is located and actions is used to instruct zoo how to behave on specific events. 

For now there is only one event called on-exists. This instructs zoo what to do if the project is already registered. Possible values are update and skip.

**Comment by aexvir** [comment]
Hmm, I like the idea of being able to store this info in the repos. It would help with a more precise discovery and the info might be easier to be kept up to date.

Just a couple thoughts:

* Not so sure about the actions part, I'd rather have a fixed logic for it, if there is a yaml file we just respect it, populating our database with it. I don't think the complexity of having to maintain the actions part it's worth.
* In that case I'd remove the `register` level as well
* I'd remove the `zoo` level completely, it just adds an extra level without any big advantage
* The environments can support multiple URLs, so it will have to be an array:

```yaml
environments:
    - staging:
       dashboard-url: https://staging.dashboard-url.com
       urls:
           -https://staging.service-url.com
```

**Comment by imunitic** [comment]
With the changes you proposed the yaml file would looke like the following.

```yaml
type: service
name: hello-world-service
owner: johndoe
impact: profit
status: production
repository: https://git/hello-world-service.git
documentation-url: https://docu.com/hello-world-service
slack-channel: http://slack.com/channel
sentry-project: http://sentry.com/hello-world-service
sonarqube-key: hello-world-service
pager-duty-url: https://pager.com/pager/hello-world-service
tags:
  - tag1
  - tag2
  - tag3
environments:
  - staging:
      dashboard-url: https://staging.dashboard-url.com
      urls: 
        - https://staging.service-url.com
  - production:
      dashboard-url: https://production.dashboard-url.com
      urls: 
        - https://production.service-url.com
```

Yes I like this. The reason I added actions was because of our conversation about what to do if the data is already in the zoos database. But having a fixed logic is also a good approach. The zoo level was just for readability  but I'm fine with removing it also.

Question: What do you think that we treat the part with sonar and sentry the same as we did with environments ? Maybe some projects don't use either and use other tools.

So that would look like something like.

```yaml
tools:
  - sentry:
      value: http://sentry.com/hello-world-service
      description: Sentry project url
  - slack:
      value: http://slack.com/channel
      description: Slack channel
  - sonarqube:
      value: hello-world-service
      description: Sonar kube key 
  - pager-duty:
      value: https://pager-duty.com/hello-world-service
      description: Pager duty url 
```
Something like above would made zoo less specific to kiwi and more general for wider use.
Of course I am horrible at naming things so please by all means propose better naming for the values.

This would involve some code changes in the zoo database model but I don't think its too much work.
